openapi: 3.0.3

info:
  title: Event Planner API
  version: 2.0.0
servers:
  - url: http://localhost:8082/
paths:
  /auth/register:
    post:
      summary: Регистрация нового пользователя
      tags:
        - Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        default:
          description: ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/login:
    post:
      summary: Вход пользователя
      tags:
        - Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        default:
          description: ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /events/create/:id:
    post:
      summary: Создать новое мероприятие
      tags:
        - Events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventRequest'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateEventResponse'
        default:
          description:  ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /events/:id:
    get:
      summary: Получить список мероприятий
      tags:
        - Events
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListEventsResponse'
        default:
          description:  ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /contacts:
    get:
      summary: Получить список контактов
      tags:
        - Contacts
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListContactsResponse'

components:
  schemas:
    CreateEventRequest:
      type: object
      properties:
        nameEvent:
          type: string
          enum:
            - встреча
            - собрание
            - лекция
            - хакатон
            - собеседование
        shape:
          type: string
          enum:
            - очно
            - дистант
        place:
          type: string
          example: IT-5(или ссылка на zoom)
        beginTime:
          type: string
          format: 2022-07-01T15:00:00.000Z
        timeDuration:
          type: string
          description: Длительность мероприятия
          example: 1 час 30 минуты
        members:
          type: array
          items:
              type: string
          example: [1,4,5,3]
          description: массив id участников мероприятия
    CreateEventResponse:
      type: object
      properties:
        message:
          type: string
    ListEventsResponse:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
    Event:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nameEvent:
          type: string
          enum:
            - встреча
            - собрание
            - лекция
            - хакатон
            - собеседование
        shape:
          type: string
          enum:
            - очно
            - дистант
        place:
          type: string
          example: IT-5(или ссылка на zoom)
        beginTime:
          type: string
          format: 2022-07-01T15:00:00.000Z
        timeDuration:
          type: string
          description: Длительность мероприятия
          example: 1 час 30 минуты
        members:
          type: array
          items:
            type: string
          example: [ 1,4,5,3 ]
          description: массив id участников мероприятия

    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    RegisterResponse:
      type: object
      properties:
        user_id:
          type: integer
    LoginRequest:
      type: object
      properties:
        name:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        id:
          type: integer

    ListContactsResponse:
      type: object
      properties:
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'

    Contact:
      type: object
      required:
        - name
        - email
      properties:
        id:
          type: string
        name:
          type: string
          example: Иванов Иван
        email:
          type: string
    Error:
      type: object
      properties:
        message:
          type: string